### PR TITLE
Upgrade to rand 0.7.0

### LINKED ISSUE #17: Upgrade to rand 0.7.0
Using this package alongside a project that uses the latest `rand` crate, and getting an incompatibility:
```rust
   Compiling pbkdf2 v0.3.0
error[E0432]: unresolved import `rand::OsRng`
 --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/pbkdf2-0.3.0/src/simple.rs:7:12
  |
7 | use rand::{OsRng, RngCore};
  |            ^^^^^ no `OsRng` in the root
```

Solution: just upgrade the imports

### PR DESCRIPTION
**Pull request by fubuloubu**
fixes #17

### CODE REVIEW

**Comment by fubuloubu** [comment]
Failure is due to support for v1.22

Unsure if this is a requirement, but seems like an older version that should be deprecated?

**Comment by newpavlov** [comment]
Yes, rand v0.7 has MSRV equal to 1.32, so we we will have to bump minor version. I have some breaking-change API redesigns in mind, so we better bump `rand` together with this redesign.

**Comment by fubuloubu** [comment]
Any chance we can bump out this small change separately of the breaking updates? It's currently blocking me on a project. Thanks!

**Comment by fubuloubu** [comment]
Any updates on this?

**Comment by pdugre** [comment]
Any updates? It's blocking me too.

**Comment by tarcieri** [comment]
Superseded by #31

**Pull request closed without merging**
